spring:
  jpa:
    defer-datasource-initialization:

seguranca:
  chave: Mc65WL3pQwExWKSuCwXFyZkCiuWaYGN0
  algoritimo: AES/CFB/PKCS5Padding
  initVector: NXlDXBexHLFMHSgA

aplicacao:
  s3:
    buckets:
      videos-processados: "midias-processadas-testes"
      videos-nao-processados: "midias-nao-processadas-testes"
  iam:
    arn: "arn:aws:iam::000000000000:role/processamento_de_videos_test"
  sqs:
    url: "https://sqs.ab-teste-1.amazonaws.com/000000000000/fila-url-teste"